Add homework 1
olya5698/SphereCppAdvanced pull request #2
Opened 2020-10-06 20:17 UTC by olya5698

Правильным образом загружены файлы для pull requst-a.

2020-10-07 16:50 UTC, Kapitonov requested changes
Самое главное замечание. После вызова метода close() нет извенения переменных дескрипторов. После вызова данного метода я могу вызвать метод write()(писать в дескриптор, хотя не мы его сейчас отрывали) или метод close() что приведет к некорректному поведению программы. 
Пример:

    Process proc("/bin/cat");
    proc.close();
    std::ofstream f1{"tmp"};
    std::ofstream f2{"tmp"};

    std::string buf{"Unexpected behaviour"};
    proc.writeExact(buf.c_str(), buf.size());

2020-10-07 16:50 UTC, Kapitonov commented on src/process.cpp
> +            ::close(pipe2_fd[1]);
Данный блок кода повторяется несколько раз. Надо вынести в отделбную функцию.

2020-10-07 16:50 UTC, Kapitonov commented on CMakeLists.txt
> +add_executable(hw-1 src/main.cpp)
Держать в одном месте код библиотеки и код, который её использует плохая практика. Предлагаю вынести main.cpp на уровень выше. Саму библиотеку стоит поместить в папку lib.

2020-10-07 16:50 UTC, Kapitonov commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Возможно с++ 20 это перебор, поскольку проект собирается и с 17 стандартом.

2020-10-07 16:50 UTC, Kapitonov commented on src/process.cpp
> +        if (pipe(pipe1_fd) == -1) {
Поскольку вы используете :: для вызова части глобальных функций, то стоит это делать для всех.

2020-10-07 16:50 UTC, Kapitonov commented on src/process.cpp
> +        ssize_t wbytes = ::write(write_fd, data, len);
Возможно, стоит дать более читаемое название переменной.

2020-10-07 16:50 UTC, Kapitonov commented on src/process.cpp
> +        int pipe1_fd[2], pipe2_fd[2];
Лучше объявлять переменные каждую на своей строке.

2020-10-07 16:50 UTC, Kapitonov commented on src/process.cpp
> +            perror("Pipe1 Error");
На мой взгляд, более правильно использовать исключения это делает программу более управляемой. 
throw std::runtime_error("Pipe1 Error");

2020-10-07 16:50 UTC, Kapitonov commented on src/process.cpp
> +        } else {
Я так понимаю, это случай родительского процесса. Надо закрывать лишние файловые дескрипторы пайпов.

2020-10-07 18:34 UTC, olya5698 commented on src/process.cpp
> +            ::close(pipe2_fd[1]);
То есть это будет новый метод класса Process, который будет закрывать все переданные ему в аргументах дескрипторы файлов путем вызова функции ::close()?

2020-10-07 18:34 UTC, olya5698 commented on CMakeLists.txt
> +add_executable(hw-1 src/main.cpp)
Я тогда вынесу process.cpp в новую директорию lib, а main.cpp оставлю в текущей директории src. Так ведь можно сделать?

2020-10-07 18:34 UTC, olya5698 commented on CMakeLists.txt
> +set(CMAKE_CXX_STANDARD 20)
Да, пожалуй, исправлю.

2020-10-07 18:34 UTC, olya5698 commented on src/process.cpp
> +        if (pipe(pipe1_fd) == -1) {
То есть для всех используемых системных функций лучше писать их вызов через :: ? Я просто так писала для тех функций, которые переопределены в классе Process, чтобы отличать их друг от друга. Ибо другого способа я не знаю, и если он существует, мне бы хотелось его узнать.

2020-10-07 18:34 UTC, olya5698 commented on src/process.cpp
> +        ssize_t wbytes = ::write(write_fd, data, len);
Ок, переименую в bytes_written

2020-10-07 18:34 UTC, olya5698 commented on src/process.cpp
> +        int pipe1_fd[2], pipe2_fd[2];
Исправлю.

2020-10-07 18:34 UTC, olya5698 commented on src/process.cpp
> +            perror("Pipe1 Error");
Да, Вы правы. Но я спросила у a-badin, и он мне ответил вот так: "_Ошибки обрабатывать необходимо, сейчас достаточно написать какое-нибудь сообщение и завершить программу. Про обработку ошибок мы будем подробно говорить в эту пятницу_". Поэтому я сделала так, как мне было наиболее понятно. Признаю, это не самый оптимальный способ.
Попробую переделать, но не уверена, что успею до лекции в эту пятницу(

2020-10-07 18:34 UTC, olya5698 commented on src/process.cpp
> +        } else {
Да, в строках 68-71 описан родительский процесс. Дескрипторы закрою.

2020-10-07 18:36 UTC, Kapitonov commented on CMakeLists.txt
> +add_executable(hw-1 src/main.cpp)
Да, так будет нормально.

2020-10-07 18:38 UTC, Kapitonov commented on src/process.cpp
> +        if (pipe(pipe1_fd) == -1) {
Да, имеется ввиду для всех системных, если мы переопределим другую функцию, то нам не придется искать старый код и ставить ::.

2020-10-07 18:39 UTC, Kapitonov commented on src/process.cpp
> +            perror("Pipe1 Error");
По сути throw std::runtime_error("Pipe1 Error"); ровно это и сделает.

2020-10-07 18:55 UTC, olya5698 commented on src/process.cpp
> +            perror("Pipe1 Error");
Насколько я понимаю, для обработки этого throw надо будет дополнительно добавить try - catch где-то в код, так ведь? Или поскольку это стандартное исключение, это не понадобится?

2020-10-07 19:00 UTC, Kapitonov commented on src/process.cpp
> +            ::close(pipe2_fd[1]);
Да, вполне подойдёт

2020-10-07 19:00 UTC, Kapitonov commented on CMakeLists.txt
> +add_executable(hw-1 src/main.cpp)
Да, вполне.

2020-10-08 19:01 UTC, Kapitonov requested changes

2020-10-08 19:01 UTC, Kapitonov commented on include/process.hpp
> +        void close_fd(std::vector<int>& fd_for_close);
Лучше передавать по константной сылке, если не меняем значения.

2020-10-08 19:01 UTC, Kapitonov commented on lib/process.cpp
> +                Process::close_fd(vector_fd);
Можно сразу писать Process::close_fd({pipe1_fd[0], pipe1_fd[1], pipe2_fd[0], pipe2_fd[1]});
В новых стандартах есть конструктор вектора из  std::initializer_list.

2020-10-08 19:01 UTC, Kapitonov commented on lib/process.cpp
> +        ssize_t bytes_read = 0;
Тут достатточно будет size_t, поскольку метод read возвращает size_t.

2020-10-08 19:01 UTC, Kapitonov commented on lib/process.cpp
> +            bytes_written += Process::write(data_start, len - bytes_written);
Можно писать без Process::

2020-10-08 19:01 UTC, Kapitonov commented on lib/process.cpp
> +            bytes_read += Process::read(data_start, len - bytes_read);
Можно писать без Process::

2020-10-08 19:01 UTC, Kapitonov commented on lib/process.cpp
> +        Process::close_fd(vector_fd);
методы класса можно ипользовать без Process::

2020-10-08 20:55 UTC, olya5698 commented on include/process.hpp
> +        void close_fd(std::vector<int>& fd_for_close);
Так я же меняю значения элементов вектора, помечая дескрипторы как закрытые...

2020-10-08 21:35 UTC, olya5698 commented on lib/process.cpp
> +                Process::close_fd(vector_fd);
У меня на такое ошибка выпадает:
SphereCppAdvanced/lib/process.cpp: In constructor ‘hw1_process::Process::Process(const string&)’:
SphereCppAdvanced/lib/process.cpp:29:48: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘std::vector<int>&’
   29 |             close_fd({pipe1_fd[0], pipe1_fd[1]});
      |                                                ^
Я понимаю, что это из-за того, что функция у меня имеет прототип void close_fd(std::vector<int>& fd_for_close); а я передаю <brace-enclosed initializer list> (что не есть то же самое, что std::initializer_list), но пока не знаю, как это исправить.

2020-10-08 21:40 UTC, Kapitonov commented on include/process.hpp
> +        void close_fd(std::vector<int>& fd_for_close);
Когда вы создаёте вектор, то вы кладёте значения, а не ссылки на элементы, так что дескрипторы реально не инвалидируются.

2020-10-09 08:06 UTC, Kapitonov requested changes

2020-10-09 08:06 UTC, Kapitonov commented on lib/process.cpp
> +        for (int i = 0; i < fd_for_close.size(); i++) {
С точки зрения современного c++, тут больше попдойдет ranged-based for (https://en.cppreference.com/w/cpp/language/range-for).

2020-10-09 08:06 UTC, Kapitonov commented on include/process.hpp
> +        int read_fd;
У членов класа должно быть _ или m, как рассказывали на лекции.

2020-10-09 08:06 UTC, Kapitonov commented on src/main.cpp
> +        path = "/usr/bin/date";
Возможно, лучше будет сделать path1 и path2, так становится понятнее.

2020-10-09 08:06 UTC, Kapitonov commented on src/main.cpp
> +    try {
Предлагаю сделать отдельные блоки try catch на каждый процесс.

2020-10-09 08:52 UTC, olya5698 commented on src/main.cpp
> +    try {
В принципе это разумно. Но в нашем случае я всегда обрабатываю исключение одного типа std::runtime_error; если исключение выбрасывается в блоке try, то обратно в блок выполнение программы все равно не возвращается. Так что в конкретно этом случае я подумала, что можно обойтись одним try-catch блоком, а не обертывать в них каждую строку обращения к объектам класса Process в файле main.cpp.

2020-10-09 09:09 UTC, Kapitonov commented on src/main.cpp
> +    try {
Я имеюю ввиду не каждую строчку, а отдельно блок с первым процессом и отдельно блок работы со вторым процессом. Также первые строки следует тоже включить в блок с первым процессом.
Можно, вообще, отдельно вынести каждый блок в отдельную функцию, к примеру test_simple_cat_process, test_date_process. Но это не обязательно.

2020-10-13 18:02 UTC, Kapitonov requested changes

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/CMakeLists.txt
> +add_library(process lib/src/process.cpp)
Лучше в папке сделать свой CMakeLists и добавить папку через  add_subdirectory.

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +            if (::execl(path.c_str(), path.c_str(), nullptr) == -1) {
Можно без if, поскольку если execl пройдет дальнейший код выполнен не будет.

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +                write_fd_ = -1;
\*

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +            write_fd_ = -1;
\*

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +                write_fd_ = -1;
Так же, не надо инвалидирвать дескрипторы. У вас вызовется деструктор и он закроет и инвалидирует все.

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +            write_fd_ = -1;
Зачем инвалидируются дескрипторы, в случае чего мы их не сможем закрыть?

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +                throw std::runtime_error("Kill Error");
Наверное, тут стоит обнулить proc_pid_.

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +                throw std::runtime_error("Waitpid Error");
Так же лучше обнулить.

2020-10-13 18:02 UTC, Kapitonov commented on HW-1/lib/src/process.cpp
> +                throw std::runtime_error("Close Error");
Что произойдет если во время вызова деструктора, мы выбросим исключение при закрытии первого дескриптора? Скорее всего утечка. Давайте уберем исключение тут.

2020-10-14 06:54 UTC, olya5698 commented on HW-1/CMakeLists.txt
> +add_library(process lib/src/process.cpp)
Добавила в папку lib свой CMakeLists.txt

2020-10-16 15:03 UTC, Kapitonov requested changes
Слейте после исправления в осноную ветку.

2020-10-16 15:03 UTC, Kapitonov commented on HW-1/lib/include/process.hpp
> +        void close_fd(std::vector<int> fd_for_close);
Если не предполагается использовать извне, то лучше убрать в приватную секцию.

2020-10-17 16:19 UTC, merged