Add homework 2
olya5698/SphereCppAdvanced pull request #3
Opened 2020-10-11 22:03 UTC by olya5698

Первая версия логгера. Пока без глобальных функций и singleton Logger. Хочется выяснить, насколько все корректно на текущем этапе. И если реализация явно неправильная и не удовлетворяет базовой безопасности исключений или диаграмме классов, то исправить это уже сейчас. Также не уверена, что везде правильно поставила ключевые слова explicit, default и override. 
На портале пока не вижу, куда надо прикреплять ссылку на этот pull request. Как только раздел с ДЗ-2 там появится, ссылку добавлю.

2020-10-16 18:03 UTC, a-badin requested changes

2020-10-16 18:03 UTC, a-badin commented on HW-2/log/include/BaseLogger.hpp
> +	    explicit BaseLogger() noexcept;
не нужно

2020-10-16 18:03 UTC, a-badin commented on HW-2/log/include/Exception.hpp
> +	    std::string err_msg_;
using std::runtime_error::runtime_error

2020-10-16 18:03 UTC, a-badin commented on HW-2/log/include/Logger.hpp
> +        ~Logger() noexcept = default;
noexcept по умолчанию

2020-10-16 18:03 UTC, a-badin commented on HW-2/log/src/LoggerFunctions.cpp
> +        Logger::get_instance().set_global_logger(std::move(std::make_unique<StdoutLogger>(log_level)));
что делает std::move

2020-10-17 18:40 UTC, olya5698 commented on HW-2/log/src/LoggerFunctions.cpp
> +        Logger::get_instance().set_global_logger(std::move(std::make_unique<StdoutLogger>(log_level)));
std::move() --- функция, которая конвертирует передаваемый ей l-value аргумент в r-value. Такая конвертация  позволяет использовать семантику перемещения вместо семантики копирования, что гораздо эффективнее. То есть прокомментированный код работает и без std::move(), но текущая реализация оптимальней.

2020-10-20 15:30 UTC, a-badin approved these changes

2020-10-20 15:30 UTC, a-badin commented on HW-2/log/src/LoggerFunctions.cpp
> +        Logger::get_instance().set_global_logger(std::move(std::make_unique<StdoutLogger>(log_level)));
Вы не совсем правы, std::make_unique - это функция. Любая функция если она не возвращает значение по ссылке, возвращает rvalue значние, при присваивании rvalue значения вызывается семантика перемещения. Значить кастить его к rvalue еще раз не нужно, это просто лишнее действие

2020-10-20 15:30 UTC, a-badin commented on HW-2/log/include/Level.hpp
> +	const char* get_level(Level& log_level);
В приниципе, вы могли бы определить эту фукнцию целиком в BaseLogger.cpp. В отрыве от реализации логгера она не очень нужна

2020-10-20 20:40 UTC, olya5698 commented on HW-2/log/src/LoggerFunctions.cpp
> +        Logger::get_instance().set_global_logger(std::move(std::make_unique<StdoutLogger>(log_level)));
То есть std::move() в 29й строке кода лишний? 
Ведь std::make_unique<Т>(arg) --- сonstructs an object of type T and wraps it in a std::unique_ptr. То есть эта функция возвращает указатель std::unique_ptr<Т> на объект типа Т, проинициализированный значениями arg. Для std::unique_ptr, насколько я поняла, семантика копирования по умолчанию отключена, ибо он разработан с учетом семантики перемещения. Соответственно, раз я хочу передать содержимое, управляемое std::unique_ptr в функцию, то передать std::unique_ptr по-хорошему мне нужно по значению, то есть с помощью функции std::move(). Нет?

2020-10-21 09:05 UTC, merged