Add homework 3
olya5698/SphereCppAdvanced pull request #4
Opened 2020-10-22 22:34 UTC by olya5698

Первая версия клиента и сервера. Не до конца уверена, что все работает корректно.

2020-10-23 19:16 UTC, Kapitonov requested changes

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/src/client.cpp
> +        connection.writeExact(msg.c_str(), msg_size);
Если начали использовать .data(), то надо продолжать её использовать. .data() и .s_str() синонимы.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/src/client.cpp
> +        connection.write(msg.c_str(), msg_size);
Если начали использовать .data(), то надо продолжать её использовать. .data() и .s_str() синонимы.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/include/Connection.hpp
> +        Connection(int fd);
explicit

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +    Descriptor::Descriptor(int fd) noexcept : fd_(fd) {}
Возможна утечка памяти, если не забирать владение дескритром, или не копировать его.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/include/Descriptor.hpp
> +        int fd_;
По умолчанию надо инициализировать невалидным значением.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +        : fd_(std::move(other_fd.fd_)) {}
Вы копируете просто число, при уничтожении other_fd произойдет закрытие и fd_ будет указывать на закрытый дескриптор валидным значением.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +        fd_ = std::move(other_fd.fd_);
std::swap()

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +            close();
У вас close noexcept, надо убрать try catch.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +        if (fd_ != -1) {
Бессмысленный if/

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +    	close();
Отступы.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +    void Connection::connect(const std::string& addr, uint16_t port) {
Что произойдет если вызвать 2 раз с разными параметрами?

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +        ssize_t bytes_written = 0;
Почему ssize_t, если ваш write возвращает size_t.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +            size_t bytes_written_part = write(data, len - bytes_written);
Не изменяется указатель на незаписанные данные.

2020-10-23 19:16 UTC, Kapitonov commented on HW-3/tcp/src/Server.cpp
> +    void Server::open(const std::string& addr, uint16_t port, int max_connection) {
Рассмотреть вариант множественного вызова данного метода.

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/src/Descriptor.cpp
> +    Descriptor::Descriptor(int fd) noexcept : fd_(fd) {}
Если честно, все еще не понимаю, в чем тут проблема. Я же просто создаю объект Descriptor, у которого fd_ = fd. 

Попробовала сделать копирование дескриптора наподобие кода ниже, но тут вылетает ошибка _EBADF oldfd isn't an open file descriptor_ при вызове функции `::dup2()`.
```
Descriptor::Descriptor(int fd) noexcept {
    if (fd >= 0) {
        ::dup2(fd, fd_);
        ::close(fd);
    } else {
        fd_ = fd;
    }
}
```
Или здесь что-то иное предполагается?

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/include/Descriptor.hpp
> +        int fd_;
Вот так вот, например: `Descriptor::Descriptor() noexcept : fd_(-1) {}` ?

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/src/Descriptor.cpp
> +        : fd_(std::move(other_fd.fd_)) {}
Здесь такая логика должна быть:
```
Descriptor::Descriptor(Descriptor&& other_fd) noexcept {
    fd_ = std::move(other_fd.fd_);
    other_fd.set_fd(-1);
}
```
?

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/src/Descriptor.cpp
> +        fd_ = std::move(other_fd.fd_);
Судя по описанию [https://www.cplusplus.com/reference/algorithm/swap/](https://www.cplusplus.com/reference/algorithm/swap/), `std::swap()` реализуется через `std::move()`. Так что мне кажется, здесь он будет излишним. 
Также не очень понимаю, каким образом предполагается его здесь использовать? Вот так: `std::swap(fd_, other_fd.fd_)`?

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/src/Connection.cpp
> +    void Connection::connect(const std::string& addr, uint16_t port) {
Самым первым вызовом в теле этой функции (чтобы не кидать исключения), я так понимаю, нужно сделать вызов метода `close();`
Тогда текущее соединение будет закрыто, и создастся новое, с которым дальше продолжится работа.

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/src/Connection.cpp
> +            size_t bytes_written_part = write(data, len - bytes_written);
А строка 96 разве не это делает?..

2020-10-25 15:10 UTC, olya5698 commented on HW-3/tcp/src/Server.cpp
> +    void Server::open(const std::string& addr, uint16_t port, int max_connection) {
Тоже `close();` вызвать в самом начале, насколько я понимаю...

2020-10-26 07:16 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +    Descriptor::Descriptor(int fd) noexcept : fd_(fd) {}
Проблема в том, что я могу передать дескриптор, а потом удалить его внешне. Есть метод newfd = dup(oldfd).

2020-10-26 07:17 UTC, Kapitonov commented on HW-3/tcp/include/Descriptor.hpp
> +        int fd_;
Да, чтобы я не мог делать всякие вызовы.

2020-10-26 07:18 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +        fd_ = std::move(other_fd.fd_);
Можно оставить через move.

2020-10-26 07:29 UTC, Kapitonov commented on HW-3/tcp/src/Descriptor.cpp
> +        : fd_(std::move(other_fd.fd_)) {}
Да, вполне нормальный вариант.

2020-10-26 07:30 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +    void Connection::connect(const std::string& addr, uint16_t port) {
Да, также можно сделать проверку, что у вас не открыто какое-то соединение, и если открыто кидать исключение. Все на ваш вкус и цвет.

2020-10-26 07:31 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +            size_t bytes_written_part = write(data, len - bytes_written);
Пропустил, видимо.

2020-10-26 07:32 UTC, Kapitonov commented on HW-3/tcp/src/Server.cpp
> +    void Server::open(const std::string& addr, uint16_t port, int max_connection) {
Да, как вариант.

2020-10-30 13:48 UTC, Kapitonov requested changes

2020-10-30 13:48 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +            throw std::runtime_error("Invalid IP host address in connection");
А обеспечивается ли строгая безопасность?

2020-11-03 16:30 UTC, Kapitonov requested changes
Давайте введем для своих классов, свои исключения, хотябы для descroptor и connection. После этого все будет готово.

2020-11-06 16:16 UTC, Kapitonov requested changes

2020-11-06 16:16 UTC, Kapitonov commented on HW-3/tcp/src/Connection.cpp
> +    void Connection::connect(const std::string& addr, uint16_t port) {
Сделать проверку значения порта.

2020-11-06 19:58 UTC, olya5698 commented on HW-3/tcp/src/Connection.cpp
> +    void Connection::connect(const std::string& addr, uint16_t port) {
Пришли к выводу, что проверка значения порта не нужна в силу приведения типа к uint16_t.

2020-11-06 19:59 UTC, merged